CREATE TABLE `EMPLOYEE_MASTER` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NUMBER` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAME` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PHONE` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EMAIL` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `NUMBER` (`NUMBER`)
) 
ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `CHALLENGE_MASTER` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DESCRIPTION` varchar(125) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TAG` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATED_BY` int(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_AT`TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) 
ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TAGS_MASTER` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) 
ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `CHALLENGE_TAG_MAPPING` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `CHALLENGE` int(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TAG` int(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) 
ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `VOTES` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `CHALLENGE` int(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `UPVOTE` int(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DOWNVOTE` int(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) 
ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_unicode_ci;